import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { DEFAULT_BUN_FRONTEND_CHECK_COMMAND, DEFAULT_RUST_CHECK_COMMAND, PROJECT_TEMPLATES } from './constants.ts'
import { agentError } from './errors.ts'
import { doctorProject } from './doctor.ts'
import { frontendBuildCommand, frontendCheckCommand, isPlainStaticFrontend } from './frontend-policy.ts'
import { detectFullstackRoots, ensureDirectory, inferProjectKind, serviceNameFromCargo, serviceNameFromDir, serviceNameFromPackage } from './project.ts'
import { frontendPackageJson, frontendSource, frontendTsConfig, frontendViteEnvSource, rustApiSource } from './template-sources.ts'
import type { TemplateName } from './types.ts'

type TemplateWriter = (projectDir: string) => void
type TemplateFile = readonly [relative: string, source: string]

const TEMPLATE_WRITERS: Readonly<Record<TemplateName, TemplateWriter>> = {
  'rust-api': (projectDir): void => writeRustApiTemplate(projectDir, serviceNameFromDir(projectDir)),
  'tanstack-static-frontend': (projectDir): void => writeFrontendTemplate(projectDir, serviceNameFromDir(projectDir), '/api'),
  'fullstack-rust-tanstack': (projectDir): void => {
    writeFullstackTemplate(projectDir)
  }
}

function initProject(projectDir: string, template = ''): void {
  if (template) {
    mkdirSync(projectDir, { recursive: true, mode: 0o755 })
    createTemplate(projectDir, template)
    return
  }
  ensureDirectory(projectDir)

  const configPath = path.join(projectDir, 'tovuk.toml')
  if (existsSync(configPath)) {
    console.log('tovuk.toml already exists')
    return
  }

  const kind = inferProjectKind(projectDir)
  const source = initConfig(projectDir, kind)

  writeFileSync(configPath, source, { mode: 0o644 })
  console.log(`created ${path.relative(process.cwd(), configPath)}`)
  console.log(`detected ${kind}`)
}

function createTemplate(projectDir: string, template: string): void {
  if (!isTemplateName(template)) {
    throw agentError('invalid_template', 'Tovuk template is unknown.', `Use one of: ${[...PROJECT_TEMPLATES].join(', ')}.`, false)
  }
  TEMPLATE_WRITERS[template](projectDir)
  console.log(`created ${template} template`)
}

function writeFullstackTemplate(projectDir: string): void {
  writeRustApiTemplate(path.join(projectDir, 'api'), 'api', false)
  writeFrontendTemplate(path.join(projectDir, 'web'), 'web', '/api', false)
  writeNewFile(path.join(projectDir, 'tovuk.toml'), fullstackConfig(projectDir, { backend: 'api', frontend: 'web' }, true))
}

function writeRustApiTemplate(projectDir: string, name: string, includeConfig = true): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: TemplateFile[] = [
    ['Cargo.toml', `[package]
name = "${name}"
version = "0.1.0"
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
`],
    ['Cargo.lock', `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${name}"
version = "0.1.0"
`],
    ['src/main.rs', rustApiSource()]
  ]
  if (includeConfig) {
    files.push(['tovuk.toml', rustBackendConfig(projectDir)])
  }
  writeTemplateFiles(projectDir, files)
}

function writeFrontendTemplate(projectDir: string, name: string, apiBaseUrl: string, includeConfig = true): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: TemplateFile[] = [
    ['package.json', frontendPackageJson(name)],
    ['index.html', '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n'],
    ['src/styles.css', 'body{margin:0;font-family:system-ui,sans-serif}main{min-height:100svh;display:grid;place-items:center;padding:2rem}code{font-family:ui-monospace,monospace}\n'],
    ['src/vite-env.d.ts', frontendViteEnvSource()],
    ['src/main.tsx', frontendSource(apiBaseUrl)],
    ['tsconfig.json', frontendTsConfig()],
    ['vite.config.ts', 'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n']
  ]
  if (includeConfig) {
    files.push(['tovuk.toml', frontendConfig(projectDir, true)])
  }
  writeTemplateFiles(projectDir, files)
  console.log('run package install in the frontend directory before doctor: bun install or npm install')
}

function writeTemplateFiles(projectDir: string, files: readonly TemplateFile[]): void {
  for (const [relative, source] of files) {
    writeNewFile(path.join(projectDir, relative), source)
  }
}

function writeNewFile(file: string, source: string): void {
  if (existsSync(file)) {
    throw agentError('file_exists', `Refusing to overwrite ${path.relative(process.cwd(), file)}.`, 'Move the existing file or choose an empty directory, then retry.', false)
  }
  writeFileSync(file, source, { mode: 0o644 })
}

function initConfig(projectDir: string, kind: ReturnType<typeof inferProjectKind>): string {
  if (kind === 'fullstack') {
    const roots = detectFullstackRoots(projectDir)
    if (!roots) {
      throw agentError('fullstack_roots_missing', 'Could not find fullstack roots.', 'Create api/Cargo.toml and web/package.json or web/index.html, then retry.', false)
    }
    return fullstackConfig(projectDir, roots)
  }
  return kind === 'static_frontend'
    ? frontendConfig(projectDir)
    : rustBackendConfig(projectDir)
}

function rustBackendConfig(projectDir: string): string {
  const name = serviceNameFromCargo(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"

[build]
check = "${DEFAULT_RUST_CHECK_COMMAND}"
command = "cargo build --release"

[run]
command = "./target/release/${name}"
port = 3000
health = "/healthz"

[resources]
memory = "512mb"
cpu = "0.25"
idle_timeout_minutes = 15
`
}

function frontendConfig(projectDir: string, preferBun = false): string {
  const name = serviceNameFromPackage(projectDir) || serviceNameFromDir(projectDir)
  const frontend = frontendBuildSettings(projectDir, preferBun)
  return `name = "${name}"
kind = "static_frontend"

[build]
check = "${frontend.check}"
command = "${frontend.build}"
output = "${frontend.output}"
`
}

function fullstackConfig(projectDir: string, roots: { backend: string; frontend: string }, preferBun = false): string {
  const name = serviceNameFromDir(projectDir)
  const backendDir = path.join(projectDir, roots.backend)
  const frontendDir = path.join(projectDir, roots.frontend)
  const backendName = serviceNameFromCargo(backendDir) || serviceNameFromDir(backendDir)
  const frontend = frontendBuildSettings(frontendDir, preferBun)
  return `name = "${name}"
kind = "fullstack"

[backend]
root = "${roots.backend}"
check = "${DEFAULT_RUST_CHECK_COMMAND}"
build = "cargo build --release"
command = "./target/release/${backendName}"
port = 3000
health = "/api/healthz"

[frontend]
root = "${roots.frontend}"
check = "${frontend.check}"
build = "${frontend.build}"
output = "${frontend.output}"

[resources]
memory = "512mb"
cpu = "0.25"
idle_timeout_minutes = 15
`
}

function frontendBuildSettings(projectDir: string, preferBun: boolean): { check: string; build: string; output: string } {
  const output = isPlainStaticFrontend(projectDir) ? '.' : 'dist'
  return {
    check: preferBun && output !== '.' ? DEFAULT_BUN_FRONTEND_CHECK_COMMAND : frontendCheckCommand(projectDir),
    build: preferBun && output !== '.' ? 'bun run build' : frontendBuildCommand(projectDir),
    output
  }
}

function installProject(projectDir: string, template = ''): void {
  initProject(projectDir, template)
  doctorProject(projectDir, false)
}

function isTemplateName(value: string): value is TemplateName {
  return PROJECT_TEMPLATES.has(value)
}

export { initProject, installProject }
