import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { DEFAULT_RUST_CHECK_COMMAND, PROJECT_TEMPLATES } from './constants.ts'
import { agentError } from './errors.ts'
import { doctorProject } from './doctor.ts'
import { frontendBuildCommand, frontendCheckCommand } from './frontend-policy.ts'
import { ensureDirectory, inferProjectKind, serviceNameFromCargo, serviceNameFromDir, serviceNameFromPackage } from './project.ts'
import type { JsonObject, TemplateName } from './types.ts'

type TemplateWriter = (projectDir: string) => void
type TemplateFile = readonly [relative: string, source: string]

const TEMPLATE_WRITERS: Readonly<Record<TemplateName, TemplateWriter>> = {
  'rust-api': (projectDir): void => writeRustApiTemplate(projectDir, serviceNameFromDir(projectDir)),
  'tanstack-static-frontend': (projectDir): void => writeFrontendTemplate(projectDir, serviceNameFromDir(projectDir), '/api'),
  'fullstack-rust-tanstack': (projectDir): void => {
    writeRustApiTemplate(path.join(projectDir, 'api'), 'api')
    writeFrontendTemplate(path.join(projectDir, 'web'), 'web', 'http://localhost:3000')
  }
}

function initProject(projectDir: string, template = ''): void {
  if (template) {
    mkdirSync(projectDir, { recursive: true, mode: 0o755 })
    createTemplate(projectDir, template)
    return
  }
  ensureDirectory(projectDir)

  const configPath = path.join(projectDir, 'zerct.toml')
  if (existsSync(configPath)) {
    console.log('zerct.toml already exists')
    return
  }

  const kind = inferProjectKind(projectDir)
  const source = kind === 'static_frontend'
    ? frontendConfig(projectDir)
    : rustBackendConfig(projectDir)

  writeFileSync(configPath, source, { mode: 0o644 })
  console.log(`created ${path.relative(process.cwd(), configPath)}`)
  console.log(`detected ${kind}`)
}

function createTemplate(projectDir: string, template: string): void {
  if (!isTemplateName(template)) {
    throw agentError('invalid_template', 'Zerct template is unknown.', `Use one of: ${[...PROJECT_TEMPLATES].join(', ')}.`, false)
  }
  TEMPLATE_WRITERS[template](projectDir)
  console.log(`created ${template} template`)
}

function writeRustApiTemplate(projectDir: string, name: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: readonly TemplateFile[] = [
    ['Cargo.toml', `[package]
name = "${name}"
version = "0.1.0"
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
`],
    ['Cargo.lock', `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${name}"
version = "0.1.0"
`],
    ['src/main.rs', rustApiSource()],
    ['zerct.toml', rustBackendConfig(projectDir)]
  ]
  writeTemplateFiles(projectDir, files)
}

function writeFrontendTemplate(projectDir: string, name: string, apiBaseUrl: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: readonly TemplateFile[] = [
    ['package.json', frontendPackageJson(name)],
    ['index.html', '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n'],
    ['src/styles.css', 'body{margin:0;font-family:system-ui,sans-serif}main{min-height:100svh;display:grid;place-items:center;padding:2rem}code{font-family:ui-monospace,monospace}\n'],
    ['src/vite-env.d.ts', frontendViteEnvSource()],
    ['src/main.tsx', frontendSource(apiBaseUrl)],
    ['tsconfig.json', frontendTsConfig()],
    ['vite.config.ts', 'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n'],
    ['zerct.toml', frontendConfig(projectDir)]
  ]
  writeTemplateFiles(projectDir, files)
  console.log('run package install in the frontend directory before doctor: bun install or npm install')
}

function frontendPackageJson(name: string): string {
  return jsonSource({
    name,
    private: true,
    type: 'module',
    scripts: {
      typecheck: 'tsgo --noEmit',
      lint: 'oxlint src vite.config.ts --deny-warnings',
      build: 'vite build',
      preview: 'vite preview --host 0.0.0.0'
    },
    dependencies: {
      '@tanstack/react-router': '^1.140.0',
      react: '^19.2.1',
      'react-dom': '^19.2.1'
    },
    devDependencies: {
      '@types/node': '^24.12.3',
      '@types/react': '^19.2.7',
      '@types/react-dom': '^19.2.3',
      '@typescript/native-preview': '^7.0.0-dev.20260526.1',
      '@vitejs/plugin-react': '^5.1.1',
      oxlint: '^1.30.0',
      typescript: '^5.9.3',
      vite: '^7.2.4'
    }
  })
}

function frontendTsConfig(): string {
  return jsonSource({
    compilerOptions: {
      allowUnreachableCode: false,
      allowUnusedLabels: false,
      alwaysStrict: true,
      erasableSyntaxOnly: true,
      exactOptionalPropertyTypes: true,
      forceConsistentCasingInFileNames: true,
      isolatedModules: true,
      jsx: 'react-jsx',
      lib: ['ESNext', 'DOM'],
      module: 'ESNext',
      moduleDetection: 'force',
      moduleResolution: 'Bundler',
      noEmit: true,
      noFallthroughCasesInSwitch: true,
      noImplicitAny: true,
      noImplicitOverride: true,
      noImplicitReturns: true,
      noImplicitThis: true,
      noPropertyAccessFromIndexSignature: true,
      noUncheckedIndexedAccess: true,
      noUncheckedSideEffectImports: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      skipLibCheck: false,
      strict: true,
      strictBindCallApply: true,
      strictFunctionTypes: true,
      strictNullChecks: true,
      strictPropertyInitialization: true,
      target: 'ES2022',
      types: ['vite/client', 'node'],
      useUnknownInCatchVariables: true,
      verbatimModuleSyntax: true
    },
    include: ['src', 'vite.config.ts']
  })
}

function jsonSource(value: JsonObject): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function writeTemplateFiles(projectDir: string, files: readonly TemplateFile[]): void {
  for (const [relative, source] of files) {
    writeNewFile(path.join(projectDir, relative), source)
  }
}

function writeNewFile(file: string, source: string): void {
  if (existsSync(file)) {
    throw agentError('file_exists', `Refusing to overwrite ${path.relative(process.cwd(), file)}.`, 'Move the existing file or choose an empty directory, then retry.', false)
  }
  writeFileSync(file, source, { mode: 0o644 })
}

function rustBackendConfig(projectDir: string): string {
  const name = serviceNameFromCargo(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"

[build]
check = "${DEFAULT_RUST_CHECK_COMMAND}"
command = "cargo build --release"

[run]
command = "./target/release/${name}"
port = 3000
health = "/healthz"

[resources]
memory = "512mb"
cpu = "0.25"
idle_timeout_minutes = 15
`
}

function frontendConfig(projectDir: string): string {
  const name = serviceNameFromPackage(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"
kind = "static_frontend"

[build]
check = "${frontendCheckCommand(projectDir)}"
command = "${frontendBuildCommand(projectDir)}"
output = "dist"
`
}

function installProject(projectDir: string, template = ''): void {
  initProject(projectDir, template)
  doctorProject(projectDir, false)
}

function rustApiSource(): string {
  return `use std::{
    io::{Read, Write},
    net::{TcpListener, TcpStream},
};

fn main() -> std::io::Result<()> {
    let port = std::env::var("PORT").unwrap_or_else(|_error| "3000".to_owned());
    let listener = TcpListener::bind(format!("0.0.0.0:{port}"))?;

    for stream in listener.incoming() {
        handle(stream?)?;
    }

    Ok(())
}

fn handle(mut stream: TcpStream) -> std::io::Result<()> {
    let mut buffer = [0_u8; 2048];
    let size = stream.read(&mut buffer)?;
    let request = String::from_utf8_lossy(&buffer[..size]);
    let mut parts = request
        .lines()
        .next()
        .unwrap_or_default()
        .split_whitespace();
    let method = parts.next().unwrap_or_default();
    let path = parts.next().unwrap_or("/");
    let origin = request
        .lines()
        .find_map(|line| line.strip_prefix("Origin: "))
        .unwrap_or("*");
    let cors_origin = allowed_origin(origin);

    if method == "OPTIONS" {
        return write_response(&mut stream, "204 No Content", "", &cors_origin);
    }

    let body = if path == "/healthz" {
        r#"{"ok":true}"#
    } else {
        r#"{"message":"hello from zerct","backend":"rust"}"#
    };
    write_response(&mut stream, "200 OK", body, &cors_origin)
}

fn allowed_origin(request_origin: &str) -> String {
    let configured = std::env::var("FRONTEND_ORIGIN").unwrap_or_else(|_error| request_origin.to_owned());
    if configured == "*" || configured == request_origin {
        configured
    } else {
        "null".to_owned()
    }
}

fn write_response(
    stream: &mut TcpStream,
    status: &str,
    body: &str,
    origin: &str,
) -> std::io::Result<()> {
    write!(
        stream,
        "HTTP/1.1 {status}\\r\\ncontent-type: application/json\\r\\ncontent-length: {}\\r\\naccess-control-allow-origin: {origin}\\r\\naccess-control-allow-methods: GET, OPTIONS\\r\\naccess-control-allow-headers: content-type, authorization\\r\\nconnection: close\\r\\n\\r\\n{body}",
        body.len()
    )
}
`
}

function frontendSource(apiBaseUrl: string): string {
  return `import { createRootRoute, createRouter, RouterProvider } from '@tanstack/react-router'
import { createRoot } from 'react-dom/client'
import './styles.css'

const apiBaseUrl = import.meta.env.VITE_API_URL ?? '${apiBaseUrl}'

function App() {
  return (
    <main>
      <section>
        <h1>Zerct TanStack Frontend</h1>
        <p>Static runtime, dynamic Rust backend calls.</p>
        <code>{apiBaseUrl}</code>
      </section>
    </main>
  )
}

const rootRoute = createRootRoute({ component: App })
const router = createRouter({ routeTree: rootRoute })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (rootElement === null) {
  throw new Error('missing root element')
}

createRoot(rootElement).render(<RouterProvider router={router} />)
`
}

function frontendViteEnvSource(): string {
  return `/// <reference types="vite/client" />

interface ViteTypeOptions {
  strictImportMetaEnv: unknown
}

interface ImportMetaEnv {
  readonly VITE_API_URL?: string
}
`
}

function isTemplateName(value: string): value is TemplateName {
  return PROJECT_TEMPLATES.has(value)
}

export { initProject, installProject }
