import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { DEFAULT_RUST_CHECK_COMMAND, FRONTEND_TEMPLATE_FILES, PROJECT_TEMPLATES } from './constants.ts'
import { agentError } from './errors.ts'
import { doctorProject } from './doctor.ts'
import { frontendBuildCommand, frontendCheckCommand } from './frontend-policy.ts'
import { ensureDirectory, inferProjectKind, serviceNameFromCargo, serviceNameFromDir, serviceNameFromPackage } from './project.ts'
import type { TemplateName } from './types.ts'

function initProject(projectDir: string, template = ''): void {
  if (template) {
    mkdirSync(projectDir, { recursive: true, mode: 0o755 })
    createTemplate(projectDir, template)
    return
  }
  ensureDirectory(projectDir)

  const configPath = path.join(projectDir, 'zerct.toml')
  if (existsSync(configPath)) {
    console.log('zerct.toml already exists')
    return
  }

  const kind = inferProjectKind(projectDir)
  const source = kind === 'static_frontend'
    ? frontendConfig(projectDir)
    : rustBackendConfig(projectDir)

  writeFileSync(configPath, source, { mode: 0o644 })
  console.log(`created ${path.relative(process.cwd(), configPath)}`)
  console.log(`detected ${kind}`)
}

function createTemplate(projectDir: string, template: string): void {
  if (!isTemplateName(template)) {
    throw agentError('invalid_template', 'Zerct template is unknown.', `Use one of: ${[...PROJECT_TEMPLATES].join(', ')}.`, false)
  }
  if (template === 'rust-api') {
    writeRustApiTemplate(projectDir, serviceNameFromDir(projectDir))
  } else if (template === 'tanstack-static-frontend') {
    writeFrontendTemplate(projectDir, serviceNameFromDir(projectDir), '/api')
  } else {
    const apiDir = path.join(projectDir, 'api')
    const webDir = path.join(projectDir, 'web')
    writeRustApiTemplate(apiDir, 'api')
    writeFrontendTemplate(webDir, 'web', 'http://localhost:3000')
  }
  console.log(`created ${template} template`)
}

function writeRustApiTemplate(projectDir: string, name: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  writeNewFile(path.join(projectDir, 'Cargo.toml'), `[package]
name = "${name}"
version = "0.1.0"
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
`)
  writeNewFile(path.join(projectDir, 'Cargo.lock'), `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${name}"
version = "0.1.0"
`)
  writeNewFile(path.join(projectDir, 'src', 'main.rs'), rustApiSource())
  writeNewFile(path.join(projectDir, 'zerct.toml'), rustBackendConfig(projectDir))
}

function writeFrontendTemplate(projectDir: string, name: string, apiBaseUrl: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  writeNewFile(path.join(projectDir, 'package.json'), `{
  "name": "${name}",
  "private": true,
  "type": "module",
  "scripts": {
    "typecheck": "tsgo --noEmit",
    "lint": "oxlint src vite.config.ts --deny-warnings",
    "build": "vite build",
    "preview": "vite preview --host 0.0.0.0"
  },
  "dependencies": {
    "react": "^19.2.1",
    "react-dom": "^19.2.1",
    "@tanstack/react-router": "^1.140.0"
  },
  "devDependencies": {
    "@types/react": "^19.2.7",
    "@types/react-dom": "^19.2.3",
    "@typescript/native-preview": "^7.0.0-dev.20260526.1",
    "@vitejs/plugin-react": "^5.1.1",
    "oxlint": "^1.30.0",
    "typescript": "^5.9.3",
    "vite": "^7.2.4"
  }
}
`)
  writeFrontendTemplateFile(projectDir, 'index.html', '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n')
  writeFrontendTemplateFile(projectDir, 'src/styles.css', 'body{margin:0;font-family:system-ui,sans-serif}main{min-height:100svh;display:grid;place-items:center;padding:2rem}code{font-family:ui-monospace,monospace}\n')
  writeFrontendTemplateFile(projectDir, 'src/vite-env.d.ts', '/// <reference types="vite/client" />\n')
  writeFrontendTemplateFile(projectDir, 'src/main.tsx', frontendSource(apiBaseUrl))
  writeFrontendTemplateFile(projectDir, 'tsconfig.json', '{"compilerOptions":{"strict":true,"jsx":"react-jsx","module":"ESNext","moduleResolution":"Bundler","target":"ES2022","noEmit":true,"skipLibCheck":true},"include":["src","vite.config.ts"]}\n')
  writeFrontendTemplateFile(projectDir, 'vite.config.ts', 'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n')
  writeFrontendTemplateFile(projectDir, 'zerct.toml', frontendConfig(projectDir))
  console.log('run package install in the frontend directory before doctor: bun install or npm install')
}

function writeFrontendTemplateFile(projectDir: string, relative: string, source: string): void {
  if (!FRONTEND_TEMPLATE_FILES.has(relative)) {
    throw new Error(`unexpected template file: ${relative}`)
  }
  writeNewFile(path.join(projectDir, relative), source)
}

function writeNewFile(file: string, source: string): void {
  if (existsSync(file)) {
    throw agentError('file_exists', `Refusing to overwrite ${path.relative(process.cwd(), file)}.`, 'Move the existing file or choose an empty directory, then retry.', false)
  }
  writeFileSync(file, source, { mode: 0o644 })
}

function rustBackendConfig(projectDir: string): string {
  const name = serviceNameFromCargo(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"

[build]
check = "${DEFAULT_RUST_CHECK_COMMAND}"
command = "cargo build --release"

[run]
command = "./target/release/${name}"
port = 3000
health = "/healthz"

[resources]
memory = "512mb"
cpu = "0.25"
idle_timeout_minutes = 15
`
}

function frontendConfig(projectDir: string): string {
  const name = serviceNameFromPackage(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"
kind = "static_frontend"

[build]
check = "${frontendCheckCommand(projectDir)}"
command = "${frontendBuildCommand(projectDir)}"
output = "dist"
`
}

function installProject(projectDir: string, template = ''): void {
  initProject(projectDir, template)
  doctorProject(projectDir, false)
}

function rustApiSource(): string {
  return `use std::{
    io::{Read, Write},
    net::{TcpListener, TcpStream},
};

fn main() -> std::io::Result<()> {
    let port = std::env::var("PORT").unwrap_or_else(|_error| "3000".to_owned());
    let listener = TcpListener::bind(format!("0.0.0.0:{port}"))?;

    for stream in listener.incoming() {
        handle(stream?)?;
    }

    Ok(())
}

fn handle(mut stream: TcpStream) -> std::io::Result<()> {
    let mut buffer = [0_u8; 2048];
    let size = stream.read(&mut buffer)?;
    let request = String::from_utf8_lossy(&buffer[..size]);
    let mut parts = request
        .lines()
        .next()
        .unwrap_or_default()
        .split_whitespace();
    let method = parts.next().unwrap_or_default();
    let path = parts.next().unwrap_or("/");
    let origin = request
        .lines()
        .find_map(|line| line.strip_prefix("Origin: "))
        .unwrap_or("*");
    let cors_origin = allowed_origin(origin);

    if method == "OPTIONS" {
        return write_response(&mut stream, "204 No Content", "", &cors_origin);
    }

    let body = if path == "/healthz" {
        r#"{"ok":true}"#
    } else {
        r#"{"message":"hello from zerct","backend":"rust"}"#
    };
    write_response(&mut stream, "200 OK", body, &cors_origin)
}

fn allowed_origin(request_origin: &str) -> String {
    let configured = std::env::var("FRONTEND_ORIGIN").unwrap_or_else(|_error| request_origin.to_owned());
    if configured == "*" || configured == request_origin {
        configured
    } else {
        "null".to_owned()
    }
}

fn write_response(
    stream: &mut TcpStream,
    status: &str,
    body: &str,
    origin: &str,
) -> std::io::Result<()> {
    write!(
        stream,
        "HTTP/1.1 {status}\\r\\ncontent-type: application/json\\r\\ncontent-length: {}\\r\\naccess-control-allow-origin: {origin}\\r\\naccess-control-allow-methods: GET, OPTIONS\\r\\naccess-control-allow-headers: content-type, authorization\\r\\nconnection: close\\r\\n\\r\\n{body}",
        body.len()
    )
}
`
}

function frontendSource(apiBaseUrl: string): string {
  return `import { createRootRoute, createRouter, RouterProvider } from '@tanstack/react-router'
import { createRoot } from 'react-dom/client'
import './styles.css'

const apiBaseUrl = import.meta.env.VITE_API_URL ?? '${apiBaseUrl}'

function App() {
  return (
    <main>
      <section>
        <h1>Zerct TanStack Frontend</h1>
        <p>Static runtime, dynamic Rust backend calls.</p>
        <code>{apiBaseUrl}</code>
      </section>
    </main>
  )
}

const rootRoute = createRootRoute({ component: App })
const router = createRouter({ routeTree: rootRoute })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(<RouterProvider router={router} />)
`
}

function isTemplateName(value: string): value is TemplateName {
  return PROJECT_TEMPLATES.has(value)
}

export { initProject, createTemplate, writeRustApiTemplate, writeFrontendTemplate, writeFrontendTemplateFile, writeNewFile, rustBackendConfig, frontendConfig, installProject, rustApiSource, frontendSource, isTemplateName }
