import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { DEFAULT_RUST_CHECK_COMMAND, PROJECT_TEMPLATES } from './constants.ts'
import { agentError } from './errors.ts'
import { doctorProject } from './doctor.ts'
import { frontendBuildCommand, frontendCheckCommand } from './frontend-policy.ts'
import { ensureDirectory, inferProjectKind, serviceNameFromCargo, serviceNameFromDir, serviceNameFromPackage } from './project.ts'
import { frontendPackageJson, frontendSource, frontendTsConfig, frontendViteEnvSource, rustApiSource } from './template-sources.ts'
import type { TemplateName } from './types.ts'

type TemplateWriter = (projectDir: string) => void
type TemplateFile = readonly [relative: string, source: string]

const TEMPLATE_WRITERS: Readonly<Record<TemplateName, TemplateWriter>> = {
  'rust-api': (projectDir): void => writeRustApiTemplate(projectDir, serviceNameFromDir(projectDir)),
  'tanstack-static-frontend': (projectDir): void => writeFrontendTemplate(projectDir, serviceNameFromDir(projectDir), '/api'),
  'fullstack-rust-tanstack': (projectDir): void => {
    writeRustApiTemplate(path.join(projectDir, 'api'), 'api')
    writeFrontendTemplate(path.join(projectDir, 'web'), 'web', 'http://localhost:3000')
  }
}

function initProject(projectDir: string, template = ''): void {
  if (template) {
    mkdirSync(projectDir, { recursive: true, mode: 0o755 })
    createTemplate(projectDir, template)
    return
  }
  ensureDirectory(projectDir)

  const configPath = path.join(projectDir, 'zerct.toml')
  if (existsSync(configPath)) {
    console.log('zerct.toml already exists')
    return
  }

  const kind = inferProjectKind(projectDir)
  const source = kind === 'static_frontend'
    ? frontendConfig(projectDir)
    : rustBackendConfig(projectDir)

  writeFileSync(configPath, source, { mode: 0o644 })
  console.log(`created ${path.relative(process.cwd(), configPath)}`)
  console.log(`detected ${kind}`)
}

function createTemplate(projectDir: string, template: string): void {
  if (!isTemplateName(template)) {
    throw agentError('invalid_template', 'Zerct template is unknown.', `Use one of: ${[...PROJECT_TEMPLATES].join(', ')}.`, false)
  }
  TEMPLATE_WRITERS[template](projectDir)
  console.log(`created ${template} template`)
}

function writeRustApiTemplate(projectDir: string, name: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: readonly TemplateFile[] = [
    ['Cargo.toml', `[package]
name = "${name}"
version = "0.1.0"
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
`],
    ['Cargo.lock', `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${name}"
version = "0.1.0"
`],
    ['src/main.rs', rustApiSource()],
    ['zerct.toml', rustBackendConfig(projectDir)]
  ]
  writeTemplateFiles(projectDir, files)
}

function writeFrontendTemplate(projectDir: string, name: string, apiBaseUrl: string): void {
  mkdirSync(path.join(projectDir, 'src'), { recursive: true, mode: 0o755 })
  const files: readonly TemplateFile[] = [
    ['package.json', frontendPackageJson(name)],
    ['index.html', '<div id="root"></div><script type="module" src="/src/main.tsx"></script>\n'],
    ['src/styles.css', 'body{margin:0;font-family:system-ui,sans-serif}main{min-height:100svh;display:grid;place-items:center;padding:2rem}code{font-family:ui-monospace,monospace}\n'],
    ['src/vite-env.d.ts', frontendViteEnvSource()],
    ['src/main.tsx', frontendSource(apiBaseUrl)],
    ['tsconfig.json', frontendTsConfig()],
    ['vite.config.ts', 'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n'],
    ['zerct.toml', frontendConfig(projectDir)]
  ]
  writeTemplateFiles(projectDir, files)
  console.log('run package install in the frontend directory before doctor: bun install or npm install')
}

function writeTemplateFiles(projectDir: string, files: readonly TemplateFile[]): void {
  for (const [relative, source] of files) {
    writeNewFile(path.join(projectDir, relative), source)
  }
}

function writeNewFile(file: string, source: string): void {
  if (existsSync(file)) {
    throw agentError('file_exists', `Refusing to overwrite ${path.relative(process.cwd(), file)}.`, 'Move the existing file or choose an empty directory, then retry.', false)
  }
  writeFileSync(file, source, { mode: 0o644 })
}

function rustBackendConfig(projectDir: string): string {
  const name = serviceNameFromCargo(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"

[build]
check = "${DEFAULT_RUST_CHECK_COMMAND}"
command = "cargo build --release"

[run]
command = "./target/release/${name}"
port = 3000
health = "/healthz"

[resources]
memory = "512mb"
cpu = "0.25"
idle_timeout_minutes = 15
`
}

function frontendConfig(projectDir: string): string {
  const name = serviceNameFromPackage(projectDir) || serviceNameFromDir(projectDir)
  return `name = "${name}"
kind = "static_frontend"

[build]
check = "${frontendCheckCommand(projectDir)}"
command = "${frontendBuildCommand(projectDir)}"
output = "dist"
`
}

function installProject(projectDir: string, template = ''): void {
  initProject(projectDir, template)
  doctorProject(projectDir, false)
}

function isTemplateName(value: string): value is TemplateName {
  return PROJECT_TEMPLATES.has(value)
}

export { initProject, installProject }
