[package]
name = "hello-rust"
version = "0.1.0"
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
large_futures = "deny"
large_include_file = "deny"
large_stack_frames = "deny"
mem_forget = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_clone = "deny"
clone_on_ref_ptr = "deny"
