[registries.crates-io]
protocol = "sparse"

[build]
warnings = "deny"

[future-incompat-report]
frequency = "always"

[net]
retry = 5

[resolver]
incompatible-rust-versions = "fallback"

[http]
timeout = 120

[env]
MACOSX_DEPLOYMENT_TARGET = { value = "11.0", force = true }
