pub(crate) const RETIRED_CLI_COMMANDS: &[&str] = &[
    "new",
    "check",
    "dev",
    "deploy",
    "service",
    "logs",
    "sqlite",
    "kv",
    "queue",
    "cron",
    "state",
    "binding",
    "limits",
    "env",
    "secrets",
    "domains",
    "storage",
    "nodes",
    "init",
    "install",
    "preview",
    "capabilities",
    "me",
    "activity",
    "services",
    "overview",
    "deploys",
    "builds",
    "status",
    "inspect",
    "platform",
    "caps",
    "limit",
    "files",
    "media",
];

pub(crate) const RETIRED_HELP_COMMANDS: &[&str] = &[
    "tovuk deploy",
    "tovuk service",
    "tovuk storage",
    "tovuk sqlite",
    "tovuk queue",
];

pub(crate) const RETIRED_PUBLIC_COMMANDS: &[&str] = &[
    "tovuk new",
    "tovuk check",
    "tovuk dev",
    "tovuk deploy",
    "tovuk service",
    "tovuk logs",
    "tovuk sqlite",
    "tovuk kv",
    "tovuk queue",
    "tovuk cron",
    "tovuk state",
    "tovuk binding",
    "tovuk limits",
    "tovuk env",
    "tovuk secrets",
    "tovuk domains",
    "tovuk storage",
    "tovuk nodes",
];

pub(crate) const RETIRED_OPENAPI_CONTRACTS: &[&str] = &[
    r#""/v1/apps""#,
    r#""/v1/deploy""#,
    r#""/v1/deploys""#,
    r#""/v1/services""#,
    r#""/v1/builds""#,
    r#""/v1/capabilities""#,
    r#""/v1/usage/caps"#,
    "DeployRequest",
    "DeployResponse",
    "ServicesResponse",
    "ServiceOverviewResponse",
    "StorageObjectsResponse",
    "SqliteQueryResponse",
    "QueueMessageSendRequest",
    "CronTrigger",
    "UsageCap",
    "TovukConfig",
];

pub(crate) const RETIRED_PUBLIC_DOCS_WORDING: &[&str] =
    &["tovuk.toml", "full-stack", "static frontend"];
