#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
python_bin="$(command -v python3.11 || command -v python3)"
export TOVUK_NPM_CLI="$repo_root/packages/tovuk/src/tovuk.ts"

npm --prefix packages/tovuk ci
export PATH="$repo_root/packages/tovuk/node_modules/.bin:$PATH"
npm --prefix packages/tovuk run check
node scripts/check-package-versions.mjs
node scripts/check-cli-contract.mjs
node scripts/check-docs.mjs
node scripts/check-prose-style.mjs
scripts/check-openapi.sh
ruby -c Formula/tovuk.rb >/dev/null
if command -v brew >/dev/null 2>&1; then
  brew style Formula/tovuk.rb
fi
npm_cli_version="$(packages/tovuk/src/tovuk.ts --version)"
printf '%s\n' "$npm_cli_version"
packages/tovuk/src/tovuk.ts --help | grep -q 'tovuk support create'
packages/tovuk/src/tovuk.ts --help | grep -q 'tovuk support resolve'
packages/tovuk/src/tovuk.ts --help | grep -q 'tovuk billing checkout'
if packages/tovuk/src/tovuk.ts --json --definitely-unknown >/tmp/tovuk-unknown-flag.out 2>/tmp/tovuk-unknown-flag.err; then
  printf 'expected npm CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/tovuk-unknown-flag.err
test "$(packages/tovuk/src/tovuk.ts -V)" = "$npm_cli_version"
test "$(packages/tovuk/src/tovuk.ts --api=https://api.example.test --wait-timeout=9 --version)" = "$npm_cli_version"

"$python_bin" -m compileall -q packages/tovuk-py/src
PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --version
PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --help | grep -q 'tovuk support create'
PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --help | grep -q 'tovuk support resolve'
PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --help | grep -q 'tovuk billing checkout'
test "$(PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --api=https://api.example.test --wait-timeout=9 --version)" = "$npm_cli_version"
if PYTHONPATH=packages/tovuk-py/src "$python_bin" -m tovuk --json --definitely-unknown >/tmp/tovuk-unknown-flag.out 2>/tmp/tovuk-unknown-flag.err; then
  printf 'expected Python CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/tovuk-unknown-flag.err

cargo fmt --check --manifest-path crates/tovuk/Cargo.toml
cargo check --locked --manifest-path crates/tovuk/Cargo.toml
cargo clippy --locked --manifest-path crates/tovuk/Cargo.toml --all-targets --all-features -- -D warnings
cargo package --locked --manifest-path crates/tovuk/Cargo.toml --allow-dirty --no-verify >/dev/null
cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- --help | grep -q 'tovuk support create'
cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- --help | grep -q 'tovuk support resolve'
cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- --help | grep -q 'tovuk billing checkout'
test "$(cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- --api=https://api.example.test --wait-timeout=9 --version)" = "$npm_cli_version"
if cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- --json --definitely-unknown >/tmp/tovuk-unknown-flag.out 2>/tmp/tovuk-unknown-flag.err; then
  printf 'expected Cargo CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/tovuk-unknown-flag.err

test -f examples/hello-rust/Cargo.lock
cargo check --locked --manifest-path examples/hello-rust/Cargo.toml
cargo clippy --locked --manifest-path examples/hello-rust/Cargo.toml --all-targets --all-features -- -D warnings
packages/tovuk/src/tovuk.ts doctor examples/hello-rust --json >/dev/null

policy_fixture="$(mktemp -d)"
rust_policy_fixture="$(mktemp -d)"
plain_static_fixture="$(mktemp -d)"
fullstack_fixture="$(mktemp -d)"
trap 'rm -rf "$policy_fixture" "$rust_policy_fixture" "$plain_static_fixture" "$fullstack_fixture"' EXIT

cat >"$rust_policy_fixture/tovuk.toml" <<'EOF'
name = "missing-lints"

[run]
command = "./target/release/missing-lints"
EOF
cat >"$rust_policy_fixture/Cargo.toml" <<'EOF'
[package]
name = "missing-lints"
version = "0.1.0"
edition = "2024"
EOF
cat >"$rust_policy_fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "missing-lints"
version = "0.1.0"
EOF
mkdir -p "$rust_policy_fixture/src"
printf 'fn main() {}\n' >"$rust_policy_fixture/src/main.rs"

for command in \
  "packages/tovuk/src/tovuk.ts doctor $rust_policy_fixture --json" \
  "PYTHONPATH=packages/tovuk-py/src $python_bin -m tovuk doctor $rust_policy_fixture --json" \
  "cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- doctor $rust_policy_fixture --json"; do
  if eval "$command" >/tmp/tovuk-policy-check.json 2>/tmp/tovuk-policy-check.err; then
    printf 'expected Rust policy fixture to fail: %s\n' "$command" >&2
    exit 1
  fi
  grep -q 'cargo lints' /tmp/tovuk-policy-check.json
done

cat >"$plain_static_fixture/tovuk.toml" <<'EOF'
name = "plain-static"
kind = "static_frontend"

[build]
check = ":"
command = ":"
output = "."
EOF
cat >"$plain_static_fixture/index.html" <<'EOF'
<!doctype html>
<h1>plain static</h1>
EOF

for command in \
  "packages/tovuk/src/tovuk.ts doctor $plain_static_fixture --json" \
  "PYTHONPATH=packages/tovuk-py/src $python_bin -m tovuk doctor $plain_static_fixture --json" \
  "cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- doctor $plain_static_fixture --json"; do
  eval "$command" >/tmp/tovuk-policy-check.json
  grep -q '"ok": true' /tmp/tovuk-policy-check.json
done

cat >"$fullstack_fixture/tovuk.toml" <<'EOF'
name = "fullstack-ok"
kind = "fullstack"

[backend]
root = "api"
check = "cargo fmt --all --check && cargo check --locked && cargo clippy --locked --all-targets --all-features -- -D warnings"
build = "cargo build --release"
command = "./target/release/api"
port = 3000
health = "/api/healthz"

[frontend]
root = "web"
check = ":"
build = ":"
output = "."
EOF
mkdir -p "$fullstack_fixture/api/src" "$fullstack_fixture/web"
cat >"$fullstack_fixture/api/Cargo.toml" <<'EOF'
[package]
name = "api"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
EOF
cat >"$fullstack_fixture/api/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "api"
version = "0.1.0"
EOF
printf 'fn main() {}\n' >"$fullstack_fixture/api/src/main.rs"
cat >"$fullstack_fixture/web/index.html" <<'EOF'
<!doctype html>
<h1>fullstack static frontend</h1>
EOF

for command in \
  "packages/tovuk/src/tovuk.ts doctor $fullstack_fixture --json" \
  "PYTHONPATH=packages/tovuk-py/src $python_bin -m tovuk doctor $fullstack_fixture --json" \
  "cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- doctor $fullstack_fixture --json"; do
  eval "$command" >/tmp/tovuk-policy-check.json
  grep -q '"ok": true' /tmp/tovuk-policy-check.json
done

cat >"$policy_fixture/tovuk.toml" <<'EOF'
name = "strict-web"
kind = "static_frontend"

[build]
check = "bun ci && bun run typecheck && bun run lint"
EOF
cat >"$policy_fixture/package.json" <<'EOF'
{
  "scripts": {
    "build": "vite build",
    "typecheck": "oxlint src vite.config.ts --deny-warnings --type-aware --type-check --tsconfig tsconfig.json",
    "lint": "oxlint src && prettier --check src"
  }
}
EOF
touch "$policy_fixture/bun.lock"
mkdir -p "$policy_fixture/src"
printf 'export const ok = true\n' >"$policy_fixture/src/main.ts"

for command in \
  "packages/tovuk/src/tovuk.ts doctor $policy_fixture --json" \
  "PYTHONPATH=packages/tovuk-py/src $python_bin -m tovuk doctor $policy_fixture --json" \
  "cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- doctor $policy_fixture --json"; do
  if eval "$command" >/tmp/tovuk-policy-check.json 2>/tmp/tovuk-policy-check.err; then
    printf 'expected policy fixture to fail: %s\n' "$command" >&2
    exit 1
  fi
  grep -q 'native frontend lint' /tmp/tovuk-policy-check.json
done

cat >"$policy_fixture/package.json" <<'EOF'
{
  "scripts": {
    "build": "vite build",
    "typecheck": "oxlint src vite.config.ts --deny-warnings --type-aware --type-check --tsconfig tsconfig.json",
    "lint": "oxlint src vite.config.ts --deny-warnings"
  }
}
EOF

for command in \
  "packages/tovuk/src/tovuk.ts doctor $policy_fixture --json" \
  "PYTHONPATH=packages/tovuk-py/src $python_bin -m tovuk doctor $policy_fixture --json" \
  "cargo run --quiet --manifest-path crates/tovuk/Cargo.toml -- doctor $policy_fixture --json"; do
  if eval "$command" >/tmp/tovuk-policy-check.json 2>/tmp/tovuk-policy-check.err; then
    printf 'expected missing Fallow policy fixture to fail: %s\n' "$command" >&2
    exit 1
  fi
  grep -q 'native frontend quality gates' /tmp/tovuk-policy-check.json
done
