#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"
python_bin="$(command -v python3.11 || command -v python3)"
export ZERCT_NPM_CLI="$repo_root/packages/zerct/src/zerct.ts"

npm --prefix packages/zerct ci
export PATH="$repo_root/packages/zerct/node_modules/.bin:$PATH"
npm --prefix packages/zerct run check
node scripts/check-package-versions.mjs
node scripts/check-cli-contract.mjs
node scripts/check-docs.mjs
node scripts/check-prose-style.mjs
scripts/check-openapi.sh
ruby -c Formula/zerct.rb >/dev/null
if command -v brew >/dev/null 2>&1; then
  brew style Formula/zerct.rb
fi
packages/zerct/src/zerct.ts --version
packages/zerct/src/zerct.ts --help | grep -q 'zerct support create'
packages/zerct/src/zerct.ts --help | grep -q 'zerct support resolve'
packages/zerct/src/zerct.ts --help | grep -q 'zerct billing checkout'
if packages/zerct/src/zerct.ts --json --definitely-unknown >/tmp/zerct-unknown-flag.out 2>/tmp/zerct-unknown-flag.err; then
  printf 'expected npm CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/zerct-unknown-flag.err
test "$(packages/zerct/src/zerct.ts -V)" = "$(packages/zerct/src/zerct.ts --version)"

"$python_bin" -m compileall -q packages/zerct-py/src
PYTHONPATH=packages/zerct-py/src "$python_bin" -m zerct --version
PYTHONPATH=packages/zerct-py/src "$python_bin" -m zerct --help | grep -q 'zerct support create'
PYTHONPATH=packages/zerct-py/src "$python_bin" -m zerct --help | grep -q 'zerct support resolve'
PYTHONPATH=packages/zerct-py/src "$python_bin" -m zerct --help | grep -q 'zerct billing checkout'
if PYTHONPATH=packages/zerct-py/src "$python_bin" -m zerct --json --definitely-unknown >/tmp/zerct-unknown-flag.out 2>/tmp/zerct-unknown-flag.err; then
  printf 'expected Python CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/zerct-unknown-flag.err

cargo fmt --check --manifest-path crates/zerct/Cargo.toml
cargo check --locked --manifest-path crates/zerct/Cargo.toml
cargo clippy --locked --manifest-path crates/zerct/Cargo.toml --all-targets --all-features -- -D warnings
cargo package --locked --manifest-path crates/zerct/Cargo.toml --allow-dirty --no-verify >/dev/null
cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- --help | grep -q 'zerct support create'
cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- --help | grep -q 'zerct support resolve'
cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- --help | grep -q 'zerct billing checkout'
if cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- --json --definitely-unknown >/tmp/zerct-unknown-flag.out 2>/tmp/zerct-unknown-flag.err; then
  printf 'expected Cargo CLI unknown flag to fail\n' >&2
  exit 1
fi
grep -q '"code": "unknown_argument"' /tmp/zerct-unknown-flag.err

test -f examples/hello-rust/Cargo.lock
cargo check --locked --manifest-path examples/hello-rust/Cargo.toml
cargo clippy --locked --manifest-path examples/hello-rust/Cargo.toml --all-targets --all-features -- -D warnings
packages/zerct/src/zerct.ts doctor examples/hello-rust --json >/dev/null

policy_fixture="$(mktemp -d)"
rust_policy_fixture="$(mktemp -d)"
trap 'rm -rf "$policy_fixture" "$rust_policy_fixture"' EXIT

cat >"$rust_policy_fixture/zerct.toml" <<'EOF'
name = "missing-lints"

[run]
command = "./target/release/missing-lints"
EOF
cat >"$rust_policy_fixture/Cargo.toml" <<'EOF'
[package]
name = "missing-lints"
version = "0.1.0"
edition = "2024"
EOF
cat >"$rust_policy_fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "missing-lints"
version = "0.1.0"
EOF
mkdir -p "$rust_policy_fixture/src"
printf 'fn main() {}\n' >"$rust_policy_fixture/src/main.rs"

for command in \
  "packages/zerct/src/zerct.ts doctor $rust_policy_fixture --json" \
  "PYTHONPATH=packages/zerct-py/src $python_bin -m zerct doctor $rust_policy_fixture --json" \
  "cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- doctor $rust_policy_fixture --json"; do
  if eval "$command" >/tmp/zerct-policy-check.json 2>/tmp/zerct-policy-check.err; then
    printf 'expected Rust policy fixture to fail: %s\n' "$command" >&2
    exit 1
  fi
  grep -q 'cargo lints' /tmp/zerct-policy-check.json
done

cat >"$policy_fixture/zerct.toml" <<'EOF'
name = "strict-web"
kind = "static_frontend"

[build]
check = "bun ci && bun run typecheck && bun run lint"
EOF
cat >"$policy_fixture/package.json" <<'EOF'
{
  "scripts": {
    "build": "vite build",
    "typecheck": "tsgo --noEmit",
    "lint": "oxlint src && prettier --check src"
  }
}
EOF
touch "$policy_fixture/bun.lock"
mkdir -p "$policy_fixture/src"
printf 'export const ok = true\n' >"$policy_fixture/src/main.ts"

for command in \
  "packages/zerct/src/zerct.ts doctor $policy_fixture --json" \
  "PYTHONPATH=packages/zerct-py/src $python_bin -m zerct doctor $policy_fixture --json" \
  "cargo run --quiet --manifest-path crates/zerct/Cargo.toml -- doctor $policy_fixture --json"; do
  if eval "$command" >/tmp/zerct-policy-check.json 2>/tmp/zerct-policy-check.err; then
    printf 'expected policy fixture to fail: %s\n' "$command" >&2
    exit 1
  fi
  grep -q 'native frontend lint' /tmp/zerct-policy-check.json
done
